// tests/e2e/security/harness.ts
//
// Boot a real Bun server.ts with the auth perimeter ENABLED (no
// MKTG_STUDIO_AUTH=disabled escape hatch). Tests in this directory hit the
// real auth gate via fetch -- no mocks, no shimmed validators, no in-process
// imports. The token is generated by the server on boot, persisted to a
// per-test path, then read back for use in test fetches.
//
// Lane 1 / Wave A E2E coverage. Used by every *.test.ts in this directory.

import { spawn, type Subprocess } from "bun";
import { mkdtemp, readFile, rm, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..", "..", "..");
const BOOT_TIMEOUT_MS = 20_000;
const BOOT_POLL_MS = 100;

export interface SecurityHarness {
  /** Token written to disk by the server on boot. */
  readonly token: string;
  /** Absolute path to the token file (mode 0o600). */
  readonly tokenPath: string;
  /** Listening port (allocated per-suite, no clash). */
  readonly port: number;
  /** `http://127.0.0.1:<port>` */
  readonly baseUrl: string;
  /** Temp project root the server runs against. */
  readonly tempDir: string;
  /** Process handle. */
  readonly proc: Subprocess;
  /** Teardown: kill server, remove temp dir + token file. Idempotent. */
  teardown(): Promise<void>;
  /** HttpOnly browser-session cookie value for direct fetch assertions. */
  cookie(): { Cookie: string };
  /** Helper: bearer headers. */
  bearer(): { Authorization: string };
}

export interface HarnessOptions {
  readonly port: number;
  /** Override env passed to the server child. */
  readonly env?: Record<string, string>;
  /** Skip brand/ seeding. Default: minimal seed (helps endpoints that read brand/). */
  readonly skipBrandSeed?: boolean;
}

const BRAND_SEED: ReadonlyArray<readonly [string, string]> = [
  ["voice-profile.md", "# Brand voice\n\nTest seed.\n"],
  ["audience.md",      "# Audience\n\nTest seed.\n"],
  ["positioning.md",   "# Positioning\n\nTest seed.\n"],
  ["competitors.md",   "# Competitors\n\nTest seed.\n"],
  ["landscape.md",     "# Landscape\n\nTest seed.\n"],
  ["keyword-plan.md",  "# Keyword plan\n\nTest seed.\n"],
  ["creative-kit.md",  "# Creative kit\n\nTest seed.\n"],
  ["stack.md",         "# Stack\n\nTest seed.\n"],
  ["assets.md",        "# Assets\n\n"],
  ["learnings.md",     "# Learnings\n\n"],
];

export async function startSecurityServer(options: HarnessOptions): Promise<SecurityHarness> {
  const tempDir = await mkdtemp(join(tmpdir(), "mktg-sec-e2e-"));
  const tokenPath = join(tempDir, "studio-token");
  const dbPath = join(tempDir, "studio.sqlite");
  const brandDir = join(tempDir, "brand");

  if (!options.skipBrandSeed) {
    await mkdir(brandDir, { recursive: true });
    for (const [name, content] of BRAND_SEED) {
      await writeFile(join(brandDir, name), content);
    }
  }

  const env: Record<string, string> = {
    ...process.env,
    STUDIO_PORT: String(options.port),
    MKTG_STUDIO_TOKEN_PATH: tokenPath,
    MKTG_STUDIO_DB: dbPath,
    MKTG_PROJECT_ROOT: tempDir,
    // Critical: do NOT set MKTG_STUDIO_AUTH=disabled. The whole point of this
    // suite is to verify the real auth gate.
    ...(options.env ?? {}),
  };
  delete env.MKTG_STUDIO_AUTH;
  delete env.MKTG_STUDIO_TOKEN; // force the file path, not env override

  const proc = spawn({
    cmd: ["bun", "run", "server.ts"],
    cwd: REPO_ROOT,
    env,
    stdout: "pipe",
    stderr: "pipe",
  });

  const baseUrl = `http://127.0.0.1:${options.port}`;
  const start = Date.now();
  while (Date.now() - start < BOOT_TIMEOUT_MS) {
    try {
      const r = await fetch(`${baseUrl}/api/health`);
      if (r.ok) break;
    } catch {
      // retry
    }
    await Bun.sleep(BOOT_POLL_MS);
  }
  // If we exited the loop without health, /api/health below will throw and
  // the test sees a real failure with the server log.

  const token = (await readFile(tokenPath, "utf-8")).trim();
  if (!token || token.length < 32) {
    proc.kill("SIGKILL");
    throw new Error(
      `studio-token not generated at ${tokenPath} (got len=${token.length}). ` +
      `Boot may have failed. Check server stderr.`,
    );
  }

  let torn = false;
  const teardown = async (): Promise<void> => {
    if (torn) return;
    torn = true;
    proc.kill("SIGINT");
    try {
      await Promise.race([proc.exited, Bun.sleep(3_000)]);
    } catch {
      // ignored
    }
    if (proc.exitCode === null) proc.kill("SIGKILL");
    try {
      await rm(tempDir, { recursive: true, force: true });
    } catch {
      // ignored
    }
  };

  return {
    token,
    tokenPath,
    port: options.port,
    baseUrl,
    tempDir,
    proc,
    teardown,
    cookie: () => ({ Cookie: `mktg_studio_session=${encodeURIComponent(token)}` }),
    bearer: () => ({ Authorization: `Bearer ${token}` }),
  };
}

/**
 * Allocate a unique port per test file. We use 38xx since other suites use
 * 39xx / 31xxx and 4xxx. Bump this list when adding a new file.
 */
export const PORTS = {
  authPerimeter:    38001,
  apiKeyRedaction:  38002,
  parseBodyStrict:  38003,
  paletteEndpoints: 38004,
  tokenRotation:    38005,
  malformedHeaders: 38006,
  mktgRun:          38007,
} as const;
