import { afterEach, describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, realpathSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { BRAND_TEMPLATES } from "../../../src/core/brand.ts";
import { CLI_BRAND_TEMPLATE_SHA256 } from "../../lib/brand-template-hashes.ts";
import {
  brandRoot,
  computeFreshness,
  looksLikeTemplate,
  resolveBrandPath,
  resolveBrandTemplateRoot,
} from "../../lib/brand-files.ts";

afterEach(() => {
  delete process.env.MKTG_PROJECT_ROOT;
  delete process.env.MKTG_BRAND_DIR;
  delete process.env.MKTG_BRAND_TEMPLATE_DIR;
  delete process.env.MARKETING_CLI_BRAND_DIR;
  delete process.env.MKTG_CLI_ROOT;
});

describe("CLI_BRAND_TEMPLATE_SHA256", () => {
  test("digests match live BRAND_TEMPLATES from the CLI package", () => {
    for (const [file, content] of Object.entries(BRAND_TEMPLATES)) {
      const digest = createHash("sha256").update(content).digest("hex");
      expect(CLI_BRAND_TEMPLATE_SHA256[file]).toBe(digest);
    }
  });
});

describe("looksLikeTemplate", () => {
  test("true for exact CLI seed content", () => {
    expect(looksLikeTemplate("voice-profile.md", BRAND_TEMPLATES["voice-profile.md"])).toBe(true);
  });

  test("false for short real content (even with leftover init-looking prose)", () => {
    const content =
      "# Voice Profile\n\n## Personality\n- Direct\n\n<!-- Generated by mktg init. Fill in. -->\n";
    expect(looksLikeTemplate("voice-profile.md", content)).toBe(false);
  });

  test("false for long customized content", () => {
    const long = "# Voice profile\n\n" + "real content. ".repeat(200);
    expect(looksLikeTemplate("voice-profile.md", long)).toBe(false);
  });
});

describe("resolveBrandTemplateRoot", () => {
  test("honors direct template-dir env override", () => {
    const tmp = mkdtempSync(join(tmpdir(), "mktg-template-dir-"));
    writeFileSync(join(tmp, "voice-profile.md"), "# template\n", "utf8");
    process.env.MKTG_BRAND_TEMPLATE_DIR = tmp;
    try {
      expect(resolveBrandTemplateRoot()).toBe(tmp);
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  test("never returns the project's own brand/ as the template root", () => {
    const project = mkdtempSync(join(tmpdir(), "mktg-self-brand-"));
    const brand = join(project, "brand");
    mkdirSync(brand, { recursive: true });
    writeFileSync(join(brand, "voice-profile.md"), "# live\n", "utf8");

    process.env.MKTG_PROJECT_ROOT = project;
    // Even if env points at the project brand, it must not be accepted.
    process.env.MKTG_BRAND_TEMPLATE_DIR = brand;
    try {
      const resolved = resolveBrandTemplateRoot(project);
      if (resolved !== null) {
        expect(realpathSync(resolved)).not.toBe(realpathSync(brand));
      }
    } finally {
      rmSync(project, { recursive: true, force: true });
    }
  });
});

describe("brandRoot", () => {
  test("uses MKTG_PROJECT_ROOT when set", () => {
    process.env.MKTG_PROJECT_ROOT = "/tmp/mktg-project-root";
    expect(brandRoot()).toBe("/tmp/mktg-project-root/brand");
  });

  test("MKTG_BRAND_DIR overrides project root", () => {
    process.env.MKTG_PROJECT_ROOT = "/tmp/mktg-project-root";
    process.env.MKTG_BRAND_DIR = "/tmp/custom-brand";
    expect(brandRoot()).toBe("/tmp/custom-brand");
  });
});

describe("resolveBrandPath", () => {
  test("accepts canonical brand file names", () => {
    const r = resolveBrandPath("voice-profile.md");
    expect(r.ok).toBe(true);
  });

  test("rejects empty / control-char names", () => {
    expect(resolveBrandPath("").ok).toBe(false);
    expect(resolveBrandPath("evil\x00.md").ok).toBe(false);
  });

  test("rejects a symlinked brand directory", () => {
    const project = mkdtempSync(join(tmpdir(), "mktg-brand-link-project-"));
    const outside = mkdtempSync(join(tmpdir(), "mktg-brand-link-outside-"));
    symlinkSync(outside, join(project, "brand"));
    try {
      const result = resolveBrandPath("voice-profile.md", project);
      expect(result.ok).toBe(false);
    } finally {
      rmSync(project, { recursive: true, force: true });
      rmSync(outside, { recursive: true, force: true });
    }
  });

  test("rejects a symlinked brand file", () => {
    const project = mkdtempSync(join(tmpdir(), "mktg-brand-file-link-"));
    const outside = join(project, "outside.md");
    mkdirSync(join(project, "brand"));
    writeFileSync(outside, "# private\n", "utf8");
    symlinkSync(outside, join(project, "brand", "voice-profile.md"));
    try {
      const result = resolveBrandPath("voice-profile.md", project);
      expect(result.ok).toBe(false);
    } finally {
      rmSync(project, { recursive: true, force: true });
    }
  });
});

describe("computeFreshness", () => {
  const now = Date.now();

  test("template flag wins over age for exact CLI seed", () => {
    const f = computeFreshness(
      "voice-profile.md",
      BRAND_TEMPLATES["voice-profile.md"],
      now,
    );
    expect(f.freshness).toBe("template");
  });

  test("short real content is fresh, not template", () => {
    const f = computeFreshness(
      "voice-profile.md",
      "# Voice\n\n## Personality\n- Direct, builder-friendly\n",
      now,
    );
    expect(f.freshness).toBe("fresh");
  });

  test("fresh content within window", () => {
    const long = "# Voice\n" + "x".repeat(2_000);
    const f = computeFreshness("voice-profile.md", long, now - 10 * 86_400_000, now);
    expect(f.freshness).toBe("fresh");
  });

  test("stale content past window", () => {
    const long = "# Voice\n" + "x".repeat(2_000);
    // voice-profile window is 90d (aligned to CLI manifest); use 91d so this
    // stays past the window even if the constant moves within reason.
    const f = computeFreshness("voice-profile.md", long, now - 91 * 86_400_000, now);
    expect(f.freshness).toBe("stale");
  });

  test("append-only files are never stale (learnings.md, assets.md)", () => {
    const long = "# Learnings\n" + "x".repeat(2_000);
    const f = computeFreshness("learnings.md", long, now - 365 * 86_400_000, now);
    expect(f.freshness).toBe("fresh");
  });

  test("append-only files never show template freshness for short custom content", () => {
    const short = "# Assets Log\n";
    const f = computeFreshness("assets.md", short, now - 10_000, now);
    expect(f.freshness).toBe("fresh");
  });
});
