// mktg — Brand directory management
// Scaffolding, freshness assessment, context matrix.

import { join } from "node:path";
import { mkdir, appendFile } from "node:fs/promises";
import {
  BRAND_FILES,
  BRAND_PROFILE_FILES,
  BRAND_APPEND_FILES,
  type BrandFile,
  type BrandBundle,
  type BrandFileStatus,
  type FreshnessLevel,
} from "../types";
import { rejectControlChars } from "./errors";

// Brand file templates — scaffolds with agent instructions for guided completion
const BRAND_TEMPLATES = {
  "voice-profile.md": `# Brand Voice Profile

<!-- Generated by mktg init. Fill in or let /cmo build this. -->

<!-- AGENT INSTRUCTIONS:
Answer these to build the voice profile:
1. What 3 adjectives describe how this brand speaks?
2. What words does this brand NEVER use?
3. If this brand were a person, who would it be?
4. Reading level? (casual / professional / technical)
Priority: Fill Voice DNA first, then Do/Don't, then Examples.
-->

## Voice DNA

- **Tone:** <!-- e.g., "Confident but not arrogant" -->
- **Personality:** <!-- e.g., "The smart friend who explains things simply" -->
- **Vocabulary:** <!-- e.g., "Technical terms OK, no jargon without explanation" -->

## Do / Don't

| Do | Don't |
|----|-------|
| <!-- e.g., "Use active voice" --> | <!-- e.g., "Use passive constructions" --> |
| <!-- e.g., "Say 'you' not 'users'" --> | <!-- e.g., "Use corporate speak" --> |

## Examples

- **Good:** <!-- e.g., "Ship faster with zero config." -->
- **Bad:** <!-- e.g., "Our solution enables accelerated deployment workflows." -->
`,
  "positioning.md": `# Positioning & Angles

<!-- Generated by mktg init. Fill in or let /cmo build this. -->

<!-- AGENT INSTRUCTIONS:
Answer these to build positioning:
1. What category does this product create or compete in?
2. Who is the primary buyer? (role, not demographics)
3. What is the ONE thing competitors can't claim?
4. What transformation does the buyer experience?
5. What is the 10-word elevator pitch?
Priority: Fill Core Positioning first, then Angles, then Proof Points.
-->

## Core Positioning

- **Category:** <!-- e.g., "Agent-native marketing CLI" -->
- **For:** <!-- e.g., "Solo founders who need marketing but don't have time" -->
- **Unlike:** <!-- e.g., "HubSpot, Jasper, generic AI writing tools" -->
- **We:** <!-- e.g., "Give your AI agent a complete CMO brain" -->

## Angles

1. <!-- e.g., "One install = full marketing department" -->
2. <!-- e.g., "Marketing that compounds across sessions" -->
3. <!-- e.g., "Built for agents, not humans" -->

## Proof Points

- <!-- e.g., "32 marketing skills, zero configuration" -->
`,
  "audience.md": `# Audience Research

<!-- Generated by mktg init. Fill in or let /cmo build this. -->

<!-- AGENT INSTRUCTIONS:
Answer these to build audience profiles:
1. Who buys this? (job title, company size, technical level)
2. What are their top 3 pain points related to this product?
3. Where do they hang out online? (subreddits, Discord, Twitter accounts)
4. What alternatives are they currently using?
5. What would make them switch immediately?
Priority: Fill Primary Audience first, then Secondary, then Watering Holes.
-->

## Primary Audience

- **Who:** <!-- e.g., "Solo founders running 2-5 projects" -->
- **Pain points:** <!-- e.g., "No time for marketing, can't afford a CMO" -->
- **Current solution:** <!-- e.g., "Manual social posts, sporadic content" -->
- **Trigger to buy:** <!-- e.g., "Realizes marketing is bottleneck to growth" -->

## Secondary Audience

- **Who:** <!-- e.g., "Developer advocates at startups" -->
- **Pain points:** <!-- e.g., "Content creation takes too long" -->

## Watering Holes

- <!-- e.g., "r/SaaS, r/indiehackers" -->
- <!-- e.g., "Indie Hackers forum" -->
- <!-- e.g., "Twitter: @levelsio, @marc_louvion" -->
`,
  "competitors.md": `# Competitive Intelligence

<!-- Generated by mktg init. Fill in or let /cmo build this. -->

<!-- AGENT INSTRUCTIONS:
Answer these for each competitor:
1. What is their core value proposition?
2. What do they charge? (pricing model + range)
3. What do their users complain about? (check G2, Reddit, Twitter)
4. What can we do that they fundamentally cannot?
5. Are they growing or declining? (traffic trends, funding)
Priority: Fill top 3 competitors first, then Gaps, then Positioning Matrix.
-->

## Competitors

### 1. <!-- e.g., "Jasper AI" -->
- **Positioning:** <!-- e.g., "AI writing assistant for marketing teams" -->
- **Pricing:** <!-- e.g., "$49/mo Creator, $125/mo Teams" -->
- **Weakness:** <!-- e.g., "No brand memory, starts fresh each session" -->

### 2. <!-- e.g., "Copy.ai" -->
- **Positioning:**
- **Pricing:**
- **Weakness:**

### 3. <!-- e.g., "HubSpot AI" -->
- **Positioning:**
- **Pricing:**
- **Weakness:**

## Our Differentiation

- <!-- e.g., "We're the only tool built for AI agents, not humans" -->
`,
  "landscape.md": `# Market Landscape

<!-- Generated by mktg init. Fill in or let /landscape-scan build this. -->

<!-- AGENT INSTRUCTIONS:
Run /landscape-scan to populate this file with live ecosystem data.
This file chains /last30days for research and validates with the user.
Priority: Claims Blacklist > Recent Shifts > Ecosystem Tools > Market Overview
-->

## Market Overview
- **Category:** <!-- e.g., "AI agent tooling" -->
- **Stage:** <!-- e.g., "Early growth — tooling consolidating" -->
- **Key Players:** <!-- Top 5-8 with one-line descriptions -->

## Recent Shifts
<!-- Last 90 days. Date each entry. Newest first. -->
- **[YYYY-MM-DD]** <!-- What changed and why it matters -->

## Ecosystem Tools
<!-- What exists RIGHT NOW. Not what existed 6 months ago. -->
| Tool | What It Does | How People Use It | Source |
|------|-------------|-------------------|--------|
| <!-- tool --> | <!-- description --> | <!-- actual usage --> | <!-- where you found this --> |

## Industry Benchmarks
<!-- Sourced data points only. No guesses. -->
- <!-- Metric: Value (Source, Date) -->

## Claims Blacklist
<!-- HARD GATE: These claims are WRONG. Do not make them in any content. -->
| Claim | Why Wrong | What To Say Instead |
|-------|-----------|---------------------|
| <!-- wrong claim --> | <!-- evidence --> | <!-- correct alternative --> |

## Claims Confirmed
<!-- These claims from brand files are VERIFIED by research. -->
- <!-- Confirmed claim (Source) -->

## Brand File Contradictions
<!-- Mismatches between landscape research and other brand files. -->
| File | Claims | Research Shows | Recommended Action |
|------|--------|---------------|-------------------|
| <!-- file --> | <!-- what it says --> | <!-- what's true --> | <!-- fix suggestion --> |

*Last updated: YYYY-MM-DD by /landscape-scan*
`,
  "keyword-plan.md": `# Keyword Plan

<!-- Generated by mktg init. Fill in or let /cmo build this. -->

<!-- AGENT INSTRUCTIONS:
Answer these to build the keyword plan:
1. What would someone Google right before buying this?
2. What questions does the target audience ask online?
3. What comparison searches exist? ("X vs Y", "X alternatives")
4. What long-tail phrases have low competition but high intent?
Priority: Fill Priority Keywords table first (5-10 rows), then Long-tail, then Content Map.
-->

## Priority Keywords

| Keyword | Intent | Difficulty | Priority |
|---------|--------|------------|----------|
| <!-- e.g., "ai marketing tool" --> | <!-- e.g., "commercial" --> | <!-- e.g., "high" --> | <!-- e.g., "P0" --> |

## Long-tail Opportunities

- <!-- e.g., "how to automate marketing for saas" -->
- <!-- e.g., "ai agent marketing automation" -->

## Content Map

| Keyword | Content Type | Status |
|---------|-------------|--------|
| <!-- e.g., "ai marketing tool" --> | <!-- e.g., "landing page" --> | <!-- e.g., "planned" --> |
`,
  "creative-kit.md": `# Creative Kit

<!-- Generated by mktg init. Fill in or let /cmo build this. -->

<!-- AGENT INSTRUCTIONS:
Answer these to build the creative kit:
1. What are the brand's primary and secondary colors? (hex codes)
2. What fonts does the brand use? (headings + body)
3. What is the visual style? (minimal, bold, playful, corporate)
4. Are there existing logos, icons, or brand assets?
5. What visual references or mood boards inspire the brand?
Priority: Fill Brand Colors first, then Typography, then Visual Style.
-->

## Brand Colors

- **Primary:** <!-- e.g., "#6366F1 (indigo)" -->
- **Secondary:** <!-- e.g., "#10B981 (emerald)" -->
- **Accent:** <!-- e.g., "#F59E0B (amber)" -->
- **Background:** <!-- e.g., "#0F172A (slate-900)" -->

## Typography

- **Headings:** <!-- e.g., "Inter Bold" -->
- **Body:** <!-- e.g., "Inter Regular, 16px" -->
- **Code:** <!-- e.g., "JetBrains Mono" -->

## Visual Style

- **Mood:** <!-- e.g., "Developer-friendly, minimal, dark mode" -->
- **Photography:** <!-- e.g., "No stock photos, use screenshots and diagrams" -->
- **Icons:** <!-- e.g., "Lucide icons, 24px stroke" -->

## Visual Brand Style

<!-- AGENT INSTRUCTIONS:
Run /visual-style to build this section. Three modes: Extract (from URL), Build (interview), Reference (mood board).
This section powers image generation via /image-gen. Without it, images are generic but functional.
Priority: Fill Primary Aesthetic first, then Lighting + Mood, then Reference Prompts.
-->

- **Primary Aesthetic:** <!-- e.g., "Swiss Design x ASCII", "warm tech minimalism", "editorial photography" -->
- **Lighting:** <!-- e.g., "rim lighting with warm tones", "soft diffused, golden hour" -->
- **Backgrounds:** <!-- e.g., "dark with warm accents", "clean white studio" -->
- **Composition:** <!-- e.g., "single focal point, generous negative space" -->
- **Mood:** <!-- e.g., "cozy futurism -- tech that feels human" -->
- **Avoid:** <!-- e.g., "generic tech imagery, cold/sterile, stock photos, floating cubes" -->
- **Reference Prompts:**
  <!-- 2-3 proven prompts that capture the brand look. Used as style anchors by /image-gen. -->
`,
  "stack.md": `# Marketing Stack

<!-- Generated by mktg init. Tools the agent can use. -->

<!-- AGENT INSTRUCTIONS:
Answer these to configure the stack:
1. What email/newsletter tool is available? (gws, Resend, Loops)
2. What social platforms to target? (Twitter, LinkedIn, Reddit)
3. What video tools are available? (Remotion, ffmpeg, ScreenStudio)
4. What analytics tools are set up? (PostHog, Plausible, GA)
5. What browser automation is available? (playwright, ply)
Priority: Fill Available Tools first, then Accounts, then Constraints.
-->

## Available Tools

- **Email:** gws
- **Social:** playwright-cli / ply
- **Video:** remotion
- **Search:** exa
- **Media:** ffmpeg

## Accounts

- <!-- e.g., "Twitter: @projecthandle" -->
- <!-- e.g., "ProductHunt: scheduled for Q2" -->

## Constraints

- <!-- e.g., "No paid ads budget yet" -->
- <!-- e.g., "Max 3 social posts per day" -->
`,
  "assets.md": `# Assets Log

<!-- Append-only. Agent adds entries as assets are created. -->

<!-- AGENT INSTRUCTIONS:
Log every asset created during marketing execution.
Format: | date | type | file/url | skill | notes |
Types: blog, social, video, email, landing-page, image, slide-deck
-->

| Date | Type | File/URL | Skill | Notes |
|------|------|----------|-------|-------|
`,
  "learnings.md": `# Marketing Learnings

<!-- Append-only. Agent records what worked and what didn't. -->

<!-- AGENT INSTRUCTIONS:
After each marketing action, log what you learned.
Format: | date | action | result | learning | next-step |
Be specific about metrics when available (CTR, views, signups).
-->

| Date | Action | Result | Learning | Next Step |
|------|--------|--------|----------|-----------|
`,
} as const satisfies Record<BrandFile, string>;

// Export for use by skill-lifecycle (template detection)
export { BRAND_TEMPLATES };

// Pre-compute template SHA-256 hashes for fast comparison
let _templateHashes: Record<BrandFile, string> | null = null;

const getTemplateHashes = (): Record<BrandFile, string> => {
  if (_templateHashes) return _templateHashes;
  const hashes = {} as Record<BrandFile, string>;
  for (const file of BRAND_FILES) {
    const hasher = new Bun.CryptoHasher("sha256");
    hasher.update(BRAND_TEMPLATES[file]);
    hashes[file] = hasher.digest("hex");
  }
  _templateHashes = hashes;
  return hashes;
};

// Check if file content matches the template (hasn't been customized)
export const isTemplateContent = (file: BrandFile, content: string): boolean => {
  const hashes = getTemplateHashes();
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(content);
  return hasher.digest("hex") === hashes[file];
};

const SCHEMA_MD_CONTENT = `# Brand Memory Schema

## Files

| File | Purpose | Required sections | Freshness | Writers |
|------|---------|-------------------|-----------|---------|
| voice-profile.md | How the brand sounds | Personality, Vocabulary, Sentence patterns | 30 days | brand-voice |
| positioning.md | Why the brand is different | Angle, Proof points, Differentiation | 30 days | positioning-angles |
| audience.md | Who the brand talks to | Personas, Pain points, Watering holes | 30 days | audience-research |
| competitors.md | Who the brand competes with | Direct, Indirect, Positioning gaps | 30 days | competitive-intel |
| landscape.md | Market snapshot | Claims, Players, Trends | 90 days | landscape-scan |
| keyword-plan.md | What people search for | Primary, Secondary, Long-tail | 90 days | keyword-research |
| creative-kit.md | Visual identity | Colors, Typography, Style anchors | 180 days | visual-style |
| stack.md | Marketing tools in use | Current tools, Integrations | 180 days | manual |
| assets.md | Created assets log | Append-only | never stale | all skills |
| learnings.md | What worked/didn't | Append-only | never stale | all skills |

## Progressive Enhancement

| Level | Context available | Behavior |
|-------|-------------------|----------|
| L0 | No brand files | Skills work with zero context. Generic output. |
| L1 | voice-profile.md | Personality-aligned output |
| L2 | + positioning + audience | Targeted, differentiated output |
| L3 | + competitors + landscape | Competitively aware output |
| L4 | All 10 files populated | Full CMO-grade output |
`;

// Scaffold brand/ directory — creates files that don't exist
export const scaffoldBrand = async (
  projectRoot: string,
  dryRun: boolean = false,
): Promise<{ created: BrandFile[]; skipped: BrandFile[]; schemaCreated: boolean }> => {
  const brandDir = join(projectRoot, "brand");
  const created: BrandFile[] = [];
  const skipped: BrandFile[] = [];

  if (!dryRun) {
    // Ensure brand/ exists
    await mkdir(brandDir, { recursive: true });
  }

  const writes: Promise<void>[] = [];

  for (const file of BRAND_FILES) {
    const filePath = join(brandDir, file);
    const bunFile = Bun.file(filePath);
    const exists = await bunFile.exists();

    if (exists) {
      skipped.push(file);
    } else {
      created.push(file);
      if (!dryRun) {
        writes.push(Bun.write(filePath, BRAND_TEMPLATES[file]).then(() => {}));
      }
    }
  }

  // Write SCHEMA.md alongside brand files (meta-document, not a BrandFile)
  const schemaPath = join(brandDir, "SCHEMA.md");
  const schemaFile = Bun.file(schemaPath);
  const schemaExists = await schemaFile.exists();
  let schemaCreated = false;

  if (!schemaExists) {
    schemaCreated = true;
    if (!dryRun) {
      writes.push(Bun.write(schemaPath, SCHEMA_MD_CONTENT).then(() => {}));
    }
  }

  // Parallel writes
  await Promise.all(writes);

  return { created, skipped, schemaCreated };
};

// Freshness assessment — pure function, no side effects
export const assessFreshness = (
  modifiedMs: number,
  reviewIntervalDays: number = 30,
): FreshnessLevel => {
  const ageDays = (Date.now() - modifiedMs) / (1000 * 60 * 60 * 24);
  if (ageDays <= reviewIntervalDays) return "current";
  return "stale";
};

// Get status of all brand files in a project
export const getBrandStatus = async (
  projectRoot: string,
  reviewIntervalDays: number = 30,
): Promise<BrandFileStatus[]> => {
  const brandDir = join(projectRoot, "brand");
  const statuses: BrandFileStatus[] = [];

  for (const file of BRAND_FILES) {
    const filePath = join(brandDir, file);
    const bunFile = Bun.file(filePath);
    const exists = await bunFile.exists();

    if (!exists) {
      statuses.push({ file, exists: false, freshness: "missing", ageDays: null });
      continue;
    }

    const [fileStat, content] = await Promise.all([
      bunFile.stat(),
      bunFile.text(),
    ]);
    const ageDays = Math.max(0, Math.floor((Date.now() - fileStat.mtimeMs) / (1000 * 60 * 60 * 24)));
    const isAppendOnly = (BRAND_APPEND_FILES as readonly string[]).includes(file);

    // Determine freshness: template > stale > current
    // Append-only files (assets.md, learnings.md) are always "current" if they exist
    let freshness: FreshnessLevel;
    if (isAppendOnly) {
      freshness = "current";
    } else if (isTemplateContent(file, content)) {
      freshness = "template";
    } else {
      freshness = assessFreshness(fileStat.mtimeMs, reviewIntervalDays);
    }

    statuses.push({ file, exists: true, freshness, ageDays });
  }

  return statuses;
};

// Check if brand/ directory exists
export const brandExists = async (projectRoot: string): Promise<boolean> => {
  const brandDir = join(projectRoot, "brand");
  try {
    const { stat } = await import("node:fs/promises");
    const s = await stat(brandDir);
    return s.isDirectory();
  } catch {
    return false;
  }
};

// Export brand/ as a portable JSON bundle
export const exportBrand = async (cwd: string): Promise<BrandBundle> => {
  const brandDir = join(cwd, "brand");
  const files: BrandBundle["files"] = {};

  const projectName = await (async () => {
    try {
      const pkg = await Bun.file(join(cwd, "package.json")).json();
      return (pkg.name as string) || cwd.split("/").pop() || "unknown";
    } catch {
      return cwd.split("/").pop() || "unknown";
    }
  })();

  await Promise.all(
    BRAND_FILES.map(async (file) => {
      const filePath = join(brandDir, file);
      const bunFile = Bun.file(filePath);
      if (!(await bunFile.exists())) return;
      const content = await bunFile.text();
      const hasher = new Bun.CryptoHasher("sha256");
      hasher.update(content);
      (files as Record<string, { content: string; sha256: string }>)[file] = {
        content,
        sha256: hasher.digest("hex"),
      };
    }),
  );

  return {
    version: 1,
    exportedAt: new Date().toISOString(),
    project: projectName,
    files,
  };
};

// Import brand files from a bundle
export const importBrand = async (
  cwd: string,
  bundle: BrandBundle,
  dryRun: boolean,
): Promise<{ imported: BrandFile[]; skipped: BrandFile[] }> => {
  const brandDir = join(cwd, "brand");
  const imported: BrandFile[] = [];
  const skipped: BrandFile[] = [];

  if (!dryRun) {
    await mkdir(brandDir, { recursive: true });
  }

  const writes: Promise<void>[] = [];

  for (const file of BRAND_FILES) {
    const entry = bundle.files[file];
    if (!entry) {
      skipped.push(file);
      continue;
    }
    imported.push(file);
    if (!dryRun) {
      writes.push(Bun.write(join(brandDir, file), entry.content).then(() => {}));
    }
  }

  await Promise.all(writes);
  return { imported, skipped };
};

// --- Brand diff / hash tracking ---

type BrandHashesFile = {
  readonly timestamp: string;
  readonly hashes: Record<string, string>;
};

type BrandDiffChange = {
  readonly file: BrandFile;
  readonly status: "added" | "modified" | "deleted" | "unchanged";
};

export type BrandDiffResult = {
  readonly baselineTimestamp: string | null;
  readonly changes: readonly BrandDiffChange[];
  readonly hasChanges: boolean;
};

export const computeBrandHashes = async (cwd: string): Promise<Record<string, string>> => {
  const brandDir = join(cwd, "brand");
  const hashes: Record<string, string> = {};
  await Promise.all(
    BRAND_FILES.map(async (file) => {
      const bunFile = Bun.file(join(brandDir, file));
      if (!(await bunFile.exists())) return;
      const content = await bunFile.text();
      const hasher = new Bun.CryptoHasher("sha256");
      hasher.update(content);
      hashes[file] = hasher.digest("hex");
    }),
  );
  return hashes;
};

export const saveBrandHashes = async (cwd: string, hashes: Record<string, string>): Promise<void> => {
  const mktgDir = join(cwd, ".mktg");
  await mkdir(mktgDir, { recursive: true });
  const data: BrandHashesFile = { timestamp: new Date().toISOString(), hashes };
  await Bun.write(join(mktgDir, "brand-hashes.json"), JSON.stringify(data, null, 2));
};

export const loadBrandHashes = async (cwd: string): Promise<BrandHashesFile | null> => {
  const filePath = join(cwd, ".mktg", "brand-hashes.json");
  const file = Bun.file(filePath);
  if (!(await file.exists())) return null;
  try {
    return await file.json() as BrandHashesFile;
  } catch {
    return null;
  }
};

export const diffBrand = async (cwd: string): Promise<BrandDiffResult> => {
  const [baseline, currentHashes] = await Promise.all([
    loadBrandHashes(cwd),
    computeBrandHashes(cwd),
  ]);

  const changes: BrandDiffChange[] = [];

  for (const file of BRAND_FILES) {
    const oldHash = baseline?.hashes[file];
    const newHash = currentHashes[file];

    if (!oldHash && !newHash) {
      // File didn't exist before, doesn't exist now — skip
      continue;
    } else if (!oldHash && newHash) {
      changes.push({ file, status: "added" });
    } else if (oldHash && !newHash) {
      changes.push({ file, status: "deleted" });
    } else if (oldHash !== newHash) {
      changes.push({ file, status: "modified" });
    } else {
      changes.push({ file, status: "unchanged" });
    }
  }

  return {
    baselineTimestamp: baseline?.timestamp ?? null,
    changes,
    hasChanges: changes.some(c => c.status !== "unchanged"),
  };
};

// --- Learning entry append ---

export type LearningEntry = {
  readonly date: string;
  readonly action: string;
  readonly result: string;
  readonly learning: string;
  readonly nextStep: string;
};

const LEARNINGS_HEADER = `# Marketing Learnings

<!-- Append-only. Agent records what worked and what didn't. -->

<!-- AGENT INSTRUCTIONS:
After each marketing action, log what you learned.
Format: | date | action | result | learning | next-step |
Be specific about metrics when available (CTR, views, signups).
-->

| Date | Action | Result | Learning | Next Step |
|------|--------|--------|----------|-----------|
`;

const validateLearningEntry = (
  entry: LearningEntry,
): { ok: true } | { ok: false; message: string } => {
  const fields: [string, string][] = [
    ["date", entry.date],
    ["action", entry.action],
    ["result", entry.result],
    ["learning", entry.learning],
    ["nextStep", entry.nextStep],
  ];
  for (const [name, value] of fields) {
    if (!value || value.trim().length === 0) {
      return { ok: false, message: `${name} cannot be empty` };
    }
    const check = rejectControlChars(value, name);
    if (!check.ok) return check;
    if (value.includes("|")) {
      return { ok: false, message: `${name} contains pipe character (|) which would break table format` };
    }
  }
  return { ok: true };
};

export const appendLearning = async (
  cwd: string,
  entry: LearningEntry,
  dryRun: boolean = false,
): Promise<{ ok: true; row: string } | { ok: false; message: string }> => {
  const validation = validateLearningEntry(entry);
  if (!validation.ok) return validation;

  const row = `| ${entry.date} | ${entry.action} | ${entry.result} | ${entry.learning} | ${entry.nextStep} |`;
  if (dryRun) return { ok: true, row };

  const brandDir = join(cwd, "brand");
  const filePath = join(brandDir, "learnings.md");

  await mkdir(brandDir, { recursive: true });

  const file = Bun.file(filePath);
  if (await file.exists()) {
    await appendFile(filePath, row + "\n");
  } else {
    await Bun.write(filePath, LEARNINGS_HEADER + row + "\n");
  }

  return { ok: true, row };
};

// Context matrix — which brand files each skill layer needs
// Skills use this to know what context to load (progressive enhancement)
export const CONTEXT_MATRIX = {
  foundation: ["voice-profile.md", "positioning.md", "audience.md", "competitors.md", "landscape.md"],
  strategy: ["voice-profile.md", "positioning.md", "audience.md", "competitors.md", "keyword-plan.md", "landscape.md"],
  execution: ["voice-profile.md", "positioning.md", "audience.md", "creative-kit.md", "landscape.md"],
  creative: ["voice-profile.md", "positioning.md", "creative-kit.md"],
  distribution: ["voice-profile.md", "audience.md", "stack.md", "landscape.md"],
} as const satisfies Record<string, readonly BrandFile[]>;
